// <auto-generated />
using FlightAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _2_DotNet_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("FlightAPI.Models.Flight", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TicketId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            TicketId = "TX-101",
                            DepartureTime = "2026-03-01T08:00:00",
                            Destination = "JFK",
                            Origin = "DEL",
                            PassengerName = "Ankit",
                            Status = "On Time"
                        },
                        new
                        {
                            TicketId = "TX-202",
                            DepartureTime = "2026-03-05T14:30:00",
                            Destination = "DXB",
                            Origin = "LHR",
                            PassengerName = "Sarah",
                            Status = "Delayed"
                        },
                        new
                        {
                            TicketId = "TX-404",
                            DepartureTime = "2026-03-01T10:30:00",
                            Destination = "LHR",
                            Origin = "BOM",
                            PassengerName = "Priya",
                            Status = "On Time"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
